version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: local.Dockerfile
    volumes:
      - .:/root
      - gems:/usr/local/bundle
    ports:
      - "9000:80"
    environment:
      - DB_ADAPTER=mysql2
      - DATABASE_URL=mysql2://root:mysql@db:3306/hello-world?sslmode=disable
    depends_on:
      - migrate
      - db

  migrate:
    build:
      context: .
      dockerfile: local.Dockerfile
    volumes:
      - .:/root
      - gems:/usr/local/bundle
    command: rails db:migrate
    environment:
      - DB_ADAPTER=mysql2
      - DATABASE_URL=mysql2://root:mysql@db:3306/hello-world?sslmode=disable
    depends_on:
      - db

  db:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DB=hello-world

volumes:
  gems: {}
