version: "3.8"

services:
  app:
    image: nullstone/rails:local
    volumes:
      - .:/app
      - gems:/usr/local/bundle
    ports:
      - "9000:80"
    environment:
      - NULLSTONE_ENV=local
      - POSTGRES_URL=postgres://postgres:postgres@db:5432/app
    depends_on:
      - db

  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app

volumes:
  gems: {}
